package com.androhunter.app.core

object Strings {

    data class StringSet(
        val appTitle: String,
        val appSubtitle: String,
        val navApps: String,
        val navTerminal: String,
        val navAdb: String,
        val navMonitor: String,
        val navWeb: String,
        val navHijack: String,
        val navAccess: String,
        val navAbout: String,
        val searchHint: String,
        val appsFound: String,
        val packageInfo: String,
        val packageLabel: String,
        val versionLabel: String,
        val sdkLabel: String,
        val debugLabel: String,
        val activitiesLabel: String,
        val receiversLabel: String,
        val servicesLabel: String,
        val providersLabel: String,
        val intentFuzzer: String,
        val contentProviders: String,
        val fileProviders: String,
        val extraKey: String,
        val extraValue: String,
        val dataUri: String,
        val launchBtn: String,
        val payloadBtn: String,
        val shellBtn: String,
        val payloadStart: String,
        val payloadRunning: String,
        val terminalTitle: String,
        val terminalHint: String,
        val terminalEmpty: String,
        val adbTitle: String,
        val adbPair: String,
        val adbConnect: String,
        val adbDisconnect: String,
        val adbQuick: String,
        val adbOutput: String,
        val broadcastTitle: String,
        val broadcastActive: String,
        val broadcastOff: String,
        val broadcastSend: String,
        val broadcastAction: String,
        val broadcastSendBtn: String,
        val broadcastLogs: String,
        val clearBtn: String,
        val webTitle: String,
        val assetLinks: String,
        val httpProbe: String,
        val quickPaths: String,
        val scanBtn: String,
        val pathScanBtn: String,
        val result: String,
        val hijackTitle: String,
        val hijackDesc: String,
        val hijackTarget: String,
        val hijackBtn: String,
        val runningTasks: String,
        val accessTitle: String,
        val accessEnable: String,
        val accessSettings: String,
        val accessFilter: String,
        val accessEvents: String,
        val aboutDeveloper: String,
        val aboutTeam: String,
        val aboutPurpose: String,
        val aboutPurposeVal: String,
        val aboutModules: String,
        val exportedLabel: String,
        val noProviders: String,
        val selectLang: String,
        val continueTxt: String,
        val dashboardTitle: String,
        val totalApps: String,
        val exportedComponents: String,
        val debugApps: String,
        val recentScans: String,
    )

    val TR = StringSet(
        appTitle = "ANDROHUNTER",
        appSubtitle = "Android Güvenlik Araç Seti v2.0",
        navApps = "Uygulamalar",
        navTerminal = "Terminal",
        navAdb = "ADB",
        navMonitor = "İzleyici",
        navWeb = "Web",
        navHijack = "Hijack",
        navAccess = "Erişim",
        navAbout = "Hakkında",
        searchHint = "paket ara...",
        appsFound = "uygulama",
        packageInfo = "PAKET BİLGİSİ",
        packageLabel = "Paket",
        versionLabel = "Versiyon",
        sdkLabel = "SDK Min",
        debugLabel = "Debug Modu",
        activitiesLabel = "Activity",
        receiversLabel = "Receiver",
        servicesLabel = "Service",
        providersLabel = "Provider",
        intentFuzzer = "INTENT FUZZER",
        contentProviders = "CONTENT PROVIDERS",
        fileProviders = "FILE PROVIDERS",
        extraKey = "Extra Anahtar",
        extraValue = "Extra Değer",
        dataUri = "Data URI (opsiyonel)",
        launchBtn = "BAŞLAT",
        payloadBtn = "PAYLOAD",
        shellBtn = "SHELL",
        payloadStart = "[ PAYLOAD BAŞLAT ]",
        payloadRunning = "ÇALIŞIYOR...",
        terminalTitle = "TERMİNAL",
        terminalHint = "komut girin...",
        terminalEmpty = "AndroHunter Terminal — komut girin veya hızlı komutlara tıklayın",
        adbTitle = "ADB YÖNETİCİ",
        adbPair = "ADB KABLOSUZ EŞLEŞTİRME",
        adbConnect = "BAĞLAN",
        adbDisconnect = "KES",
        adbQuick = "HIZLI KOMUTLAR",
        adbOutput = "ÇIKTI",
        broadcastTitle = "BROADCAST İZLEYİCİ",
        broadcastActive = "● AKTİF",
        broadcastOff = "○ KAPALI",
        broadcastSend = "ÖZEL BROADCAST GÖNDER",
        broadcastAction = "Intent Action",
        broadcastSendBtn = "[ GÖNDER ]",
        broadcastLogs = "KAYITLAR",
        clearBtn = "Temizle",
        webTitle = "WEB TEST",
        assetLinks = "ASSET LINKS KONTROL",
        httpProbe = "HTTP PROBE",
        quickPaths = "HIZLI PATH TARAMA:",
        scanBtn = "[ ASSET LINKS TARA ]",
        pathScanBtn = "[ PATH TARA ]",
        result = "SONUÇ",
        hijackTitle = "TASK HİJACKİNG",
        hijackDesc = "Hedef uygulamanın görev yığınına AndroHunter aktivitesi enjekte eder.",
        hijackTarget = "Hedef Paket",
        hijackBtn = "[ TASK HIJACK DENE ]",
        runningTasks = "ÇALIŞAN GÖREVLER",
        accessTitle = "ERİŞİLEBİLİRLİK İZLEYİCİ",
        accessEnable = "Servisi etkinleştirmek için Erişilebilirlik Ayarları'nı açın",
        accessSettings = "[ ERİŞİLEBİLİRLİK AYARLARI ]",
        accessFilter = "Pakete göre filtrele",
        accessEvents = "EVENTLER",
        aboutDeveloper = "Geliştirici",
        aboutTeam = "Takım",
        aboutPurpose = "Amaç",
        aboutPurposeVal = "Android Güvenlik Araştırması",
        aboutModules = "MODÜLLER",
        exportedLabel = "EXPORTED",
        noProviders = "Provider bulunamadı",
        selectLang = "Dil Seçin",
        continueTxt = "Devam Et",
        dashboardTitle = "PANEL",
        totalApps = "Toplam Uygulama",
        exportedComponents = "Exported Bileşen",
        debugApps = "Debug Uygulama",
        recentScans = "Son Taramalar",
    )

    val EN = StringSet(
        appTitle = "ANDROHUNTER",
        appSubtitle = "Android Security Toolkit v2.0",
        navApps = "Apps",
        navTerminal = "Terminal",
        navAdb = "ADB",
        navMonitor = "Monitor",
        navWeb = "Web",
        navHijack = "Hijack",
        navAccess = "Access",
        navAbout = "About",
        searchHint = "search package...",
        appsFound = "apps",
        packageInfo = "PACKAGE INFO",
        packageLabel = "Package",
        versionLabel = "Version",
        sdkLabel = "Min SDK",
        debugLabel = "Debug Mode",
        activitiesLabel = "Activities",
        receiversLabel = "Receivers",
        servicesLabel = "Services",
        providersLabel = "Providers",
        intentFuzzer = "INTENT FUZZER",
        contentProviders = "CONTENT PROVIDERS",
        fileProviders = "FILE PROVIDERS",
        extraKey = "Extra Key",
        extraValue = "Extra Value",
        dataUri = "Data URI (optional)",
        launchBtn = "LAUNCH",
        payloadBtn = "PAYLOAD",
        shellBtn = "SHELL",
        payloadStart = "[ START PAYLOAD ]",
        payloadRunning = "RUNNING...",
        terminalTitle = "TERMINAL",
        terminalHint = "enter command...",
        terminalEmpty = "AndroHunter Terminal — enter a command or tap quick commands",
        adbTitle = "ADB MANAGER",
        adbPair = "ADB WIRELESS PAIR",
        adbConnect = "CONNECT",
        adbDisconnect = "DISC",
        adbQuick = "QUICK COMMANDS",
        adbOutput = "OUTPUT",
        broadcastTitle = "BROADCAST MONITOR",
        broadcastActive = "● ACTIVE",
        broadcastOff = "○ INACTIVE",
        broadcastSend = "SEND CUSTOM BROADCAST",
        broadcastAction = "Intent Action",
        broadcastSendBtn = "[ SEND ]",
        broadcastLogs = "LOGS",
        clearBtn = "Clear",
        webTitle = "WEB TESTER",
        assetLinks = "ASSET LINKS CHECK",
        httpProbe = "HTTP PROBE",
        quickPaths = "QUICK PATH SCAN:",
        scanBtn = "[ SCAN ASSET LINKS ]",
        pathScanBtn = "[ SCAN PATHS ]",
        result = "RESULT",
        hijackTitle = "TASK HIJACKING",
        hijackDesc = "Injects AndroHunter activity into the target app's task stack.",
        hijackTarget = "Target Package",
        hijackBtn = "[ TRY TASK HIJACK ]",
        runningTasks = "RUNNING TASKS",
        accessTitle = "ACCESSIBILITY MONITOR",
        accessEnable = "Open Accessibility Settings to enable the service",
        accessSettings = "[ ACCESSIBILITY SETTINGS ]",
        accessFilter = "Filter by package",
        accessEvents = "EVENTS",
        aboutDeveloper = "Developer",
        aboutTeam = "Team",
        aboutPurpose = "Purpose",
        aboutPurposeVal = "Android Security Research",
        aboutModules = "MODULES",
        exportedLabel = "EXPORTED",
        noProviders = "No providers found",
        selectLang = "Select Language",
        continueTxt = "Continue",
        dashboardTitle = "DASHBOARD",
        totalApps = "Total Apps",
        exportedComponents = "Exported Components",
        debugApps = "Debug Apps",
        recentScans = "Recent Scans",
    )

    fun get(): StringSet = if (LanguageManager.isTurkish()) TR else EN
}
